### ISSUE TITLE
Seen you post in JSIAdvTransparentPod

### ISSUE THREAD

**Issue by Mecripp** [linuxgurugamer/ASET_PRC_Rover#1]
I had to use this but the whole top of rover was transparent but give it a try
and at some angles the glass was pink

MODULE
	{
		name = JSIAdvTransparentPod	
		transparentShaderName = Legacy Shaders/Transparent/ERSGlassDiffuse
                transparentTransforms = CabineGlassBottomLeftSide|CabineGlassBottomRightSide|CabineGlassCentre|CabineGlassLefSide|CabineGlassLeftSide|CabineGlassLowCenter|CabineGlassLowRightSide|CabineGlassRightSide|CabineGlassTop
	}

**Comment by linuxgurugamer** [comment]
Thanks, turns out the original author came back and released an update
