### ISSUE TITLE
The rover wheels seem to turn only when in stowed position.

### ISSUE THREAD

**Issue by parzival2** [linuxgurugamer/ASET_PRC_Rover#2]
Hi,

Great mod. The wheels seem to only turn when in stowed position and this is only when using KSP Wheel mod. Using stock it works but its very hard to control as it becomes unstable quite soon. Would be glad to provide further information, Please, let me know if you need any. 
Thanks.

**Comment by linuxgurugamer** [comment]
You probably have the wheels upside down.

Since this is a support question, please post questions in the mod thread so that others can both help and benefit from the answers

https://forum.kerbalspaceprogram.com/index.php?/topic/189044-110-portable-rover-components/
